#IMAGEN DE NGINX
FROM nginx:latest
# COPIA DE ARCHIVOS
COPY ./softy-pinko-front-end /var/www/html/softy-pinko-front-end
# COPIA DE ARCHIVOS
COPY ./softy-pinko-front-end.conf /etc/nginx/conf.d/default.conf
#PORT 9000
EXPOSE 9000